# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "mbiodev"
  config.vm.provider :virtualbox do |vb|
      vb.name = "mbiodev"
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8001, host: 8001
  config.vm.network "forwarded_port", guest: 8002, host: 8002
  config.vm.network "forwarded_port", guest: 9001, host: 9001
  config.vm.network "forwarded_port", guest: 9002, host: 9002

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y

    sudo yum install java -y
    sudo yum install wget -y
    sudo yum install git -y

    sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
    sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
    sudo yum install jenkins -y
    sudo service jenkins start
    sudo chkconfig jenkins on

    sudo yum install -y yum-utils device-mapper-persistent-data lvm2 -y
    sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    sudo yum install docker-ce -y
    sudo systemctl start docker
    sudo systemctl enable docker

    sudo usermod -a -G docker jenkins
    sudo service jenkins restart

    sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose

    sudo yum install Xvfb -y

    sudo wget -O /tmp/chrome.rpm wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    sudo yum install /tmp/chrome.rpm -y
    sudo rm /tmp/chrome.rpm

    sudo yum install unzip -y
    sudo wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
    sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
    sudo ln -s /usr/local/bin/chromedriver /usr/bin/chromedriver
    sudo rm /tmp/chromedriver.zip
  SHELL

end